---
- name: Install and configure ELK stack
  hosts: elk
  become: yes

  vars:
    elastic_version: "8.10.2"  # Specify the ELK version

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required dependencies
      apt:
        name:
          - apt-transport-https
          - openjdk-11-jdk
          - curl
          - gnupg
        state: present

    - name: Add Elasticsearch GPG key
      apt_key:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        state: present

    - name: Add Elasticsearch repository
      apt_repository:
        repo: "deb https://artifacts.elastic.co/packages/{{ elastic_version }}/apt stable main"
        state: present

    - name: Install Elasticsearch
      apt:
        name: elasticsearch
        state: present

    - name: Configure Elasticsearch
      lineinfile:
        path: /etc/elasticsearch/elasticsearch.yml
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - { regexp: '^#?network.host:', line: 'network.host: 0.0.0.0' }
        - { regexp: '^#?http.port:', line: 'http.port: 9200' }

    - name: Enable and start Elasticsearch
      service:
        name: elasticsearch
        state: started
        enabled: true

    - name: Install Logstash
      apt:
        name: logstash
        state: present

    - name: Enable and start Logstash
      service:
        name: logstash
        state: started
        enabled: true

    - name: Install Kibana
      apt:
        name: kibana
        state: present

    - name: Configure Kibana
      lineinfile:
        path: /etc/kibana/kibana.yml
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - { regexp: '^#?server.host:', line: 'server.host: "0.0.0.0"' }
        - { regexp: '^#?elasticsearch.hosts:', line: 'elasticsearch.hosts: ["http://localhost:9200"]' }

    - name: Enable and start Kibana
      service:
        name: kibana
        state: started
        enabled: true

    - name: Install Filebeat
      apt:
        name: filebeat
        state: present

    - name: Configure Filebeat
      copy:
        src: /etc/filebeat/filebeat.reference.yml
        dest: /etc/filebeat/filebeat.yml
      notify:
        - Restart Filebeat

    - name: Enable and start Filebeat
      service:
        name: filebeat
        state: started
        enabled: true

    - name: Install Metricbeat
      apt:
        name: metricbeat
        state: present

    - name: Configure Metricbeat
      copy:
        src: /etc/metricbeat/metricbeat.reference.yml
        dest: /etc/metricbeat/metricbeat.yml
      notify:
        - Restart Metricbeat

    - name: Enable and start Metricbeat
      service:
        name: metricbeat
        state: started
        enabled: true

  handlers:
    - name: Restart Filebeat
      service:
        name: filebeat
        state: restarted

    - name: Restart Metricbeat
      service:
        name: metricbeat
        state: restarted